export const PRODUCTS_FETCH_DATA_SUCCESS = 'PRODUCTS_FETCH_DATA_SUCCESS';
export const PRODUCTS_FETCH_DATA_LOADING = 'PRODUCTS_FETCH_DATA_LOADING';
export const PRODUCTS_FETCH_DATA_ERROR = 'PRODUCTS_FETCH_DATA_ERROR';

export const PRODUCT_POST_DATA_SUCCESS = 'PRODUCT_POST_DATA_SUCCESS';
export const PRODUCT_POST_DATA_LOADING = 'PRODUCT_POST_DATA_LOADING';
export const PRODUCT_POST_DATA_ERROR = 'PRODUCT_POST_DATA_ERROR';

export const CART_POST_DATA_SUCCESS = 'CART_POST_DATA_SUCCESS';
export const CART_POST_DATA_LOADING = 'CART_POST_DATA_LOADING';
export const CART_POST_DATA_ERROR = 'CART_POST_DATA_ERROR';

export const CART_DELETE_DATA_SUCCESS = 'CART_DELETE_DATA_SUCCESS';
export const CART_DELETE_DATA_LOADING = 'CART_DELETE_DATA_LOADING';
export const CART_DELETE_DATA_ERROR = 'CART_DELETE_DATA_ERROR';

export const CART_GET_DATA_SUCCESS = 'CART_GET_DATA_SUCCESS';
export const CART_GET_DATA_LOADING = 'CART_GET_DATA_LOADING';
export const CART_GET_DATA_ERROR = 'CART_GET_DATA_ERROR';

export const CART_DELETE_ALL_DATA_SUCCESS = 'CART_DELETE_ALL_DATA_SUCCESS';
export const CART_DELETE_ALL_DATA_LOADING = 'CART_DELETE_ALL_DATA_LOADING';
export const CART_DELETE_ALL_DATA_ERROR = 'CART_DELETE_ALL_DATA_ERROR';