export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    CAPTCHA_REQUEST: 'USERS_CAPTCHA_REQUEST',
    CAPTCHA_SUCCESS: 'USERS_CAPTCHA_SUCCESS',
    CAPTCHA_FAILURE: 'USERS_CAPTCHA_FAILURE',
    
    REFRESH_REQUEST: 'USERS_REFRESH_REQUEST',
    REFRESH_SUCCESS: 'USERS_REFRESH_SUCCESS',
    REFRESH_FAILURE: 'USERS_REFRESH_FAILURE',
};